[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# --connect-under-reset is important for nucleo boards with ST-Link integrated
# Change stm32f103rb to your chip name, if necessary.
runner = "probe-rs run --chip STM32F103RB --connect-under-reset"

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "trace"
